spring:
  application:
    name: bn-auth-service
  jackson:
    time-zone: ${APP_TIMEZONE:America/Sao_Paulo}
  datasource:
    url: ${POSTGRESQL_DB_URL:pgserver}
    username: ${POSTGRESQL_DB_USER:bn}
    password: ${POSTGRESQL_DB_PASSWORD:secret123}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

data:
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

security:
  oauth2:
    client:
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID:null}
          client-secret: ${GOOGLE_CLIENT_SECRET:null}
          scope:
            - email
            - profile
          redirect-uri: "${baseUrl}/login/oauth2/code/{registrationId}"

        github:
          client-id: ${GITHUB_CLIENT_ID:null}
          client-secret: ${GITHUB_CLIENT_SECRET:null}
          scope:
            -read:user
            -read:email
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

jwt:
  secret: ${JWT_SECRET:myVerySecretKeyThatIsAtLeast256BitsLongForHS256Algorithm}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME:900000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME:604800000}

server:
  port: 8080
